### ISSUE TITLE
Merkle airdrop data for 1inch airdrops

### ISSUE THREAD

**Issue by 0xalfalfa** [1inch/merkle-distribution#6]
Would you consider publishing the amounts and merkle index numbers for all addresses that received an 1inch airdrop, please?

For the Uniswap airdrop the data is readily available as a whole at https://mrkl.uniswap.org/ and chunked at https://github.com/Uniswap/mrkl-drop-data-chunks.

Your backend returns the data for **one** address through these endpoints: 

https://governance.1inch.io/v1.1/distribution/0x3e1ad9ab7cd9a3c48f8fe4ef1fe95ce9bd061294 
https://governance.1inch.io/v1.1/distribution/v2/0x3e1ad9ab7cd9a3c48f8fe4ef1fe95ce9bd061294 

However, the complete data for all addresses is not available.

Rationale: To check a batch of addresses for a claimable reward, the complete list of rewarded addresses is needed and their index number in the merkle tree, so that the function _isClaimed(index)_ on the 1inch _MerkleDistributor_ contract can be called on chain.

**Comment by ZumZoom** [comment]
Code for the dataset generation is available at https://github.com/1inch/1inch-airdrop
